# Change these first
owner: francisfontoura # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: MongoDB
    slug: mongodb
    url: https://exporters.eciga.consorciociga.gov.br/metrics
    icon: https://www.mongodb.com/assets/images/global/favicon.ico
    headers:
      - 'x-api-key: $MONGODB_EXPORTER_API_KEY'
    __dangerous__body_down_if_text_missing: 'mongodb_up{cluster_role="mongod"} 1'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.eciga.consorciociga.gov.br
  # baseUrl: /upptime
  logoUrl: https://e2.ciga.sc.gov.br/eciga.webp
  name: e-Ciga Status
  # introTitle: e-Ciga Status
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar: []
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  allSystemsOperational: Todos os sistemas estão operacionais
  averageResponseTime: Tempo médio de resposta: $TIMEms
  duration1Y: Ano
  duration24H: Últ. dia
  duration30D: Mês
  duration7D: Semana
  durationAll: Sempre
  footer: ©2025 [Consórcio de Inovação na Gestão Pública](https://consorciociga.gov.br)
  liveStatus: Status Ao Vivo
  locale: pt-BR
  overallUptime: Tempo de atividade geral: $UPTIME
