owner: francisfontoura
repo: upptime
sites:
  - name: MongoDB
    slug: mongodb
    url: https://exporters.eciga.consorciociga.gov.br/metrics
    icon: https://www.mongodb.com/assets/images/global/favicon.ico
    headers:
      - 'x-api-key: $MONGODB_EXPORTER_API_KEY'
    __dangerous__body_down_if_text_missing: 'mongodb_up{cluster_role="mongod"} 1'
status-website:
  cname: status.eciga.consorciociga.gov.br
  logoUrl: https://e2.ciga.sc.gov.br/eciga.webp
  name: e-Ciga Status
  navbar:
     - title: Sistema e-Ciga
       href: https://gateway.eciga.consorciociga.gov.br
i18n:
  allSystemsOperational: Todos os sistemas estão operacionais
  averageResponseTime: 'Tempo médio de resposta: $TIMEms'
  duration1Y: Ano
  duration24H: Últ. dia
  duration30D: Mês
  duration7D: Semana
  durationAll: Sempre
  footer: ©2025 [Consórcio de Inovação na Gestão Pública](https://consorciociga.gov.br)
  liveStatus: Status Ao Vivo
  locale: pt-BR
  overallUptime: 'Tempo de atividade geral: $UPTIME'
