owner: francisfontoura
repo: upptime
sites:
  - name: MongoDB
    slug: mongodb
    url: https://exporters.eciga.consorciociga.gov.br/metrics
    icon: https://www.mongodb.com/assets/images/global/favicon.ico
    headers:
      - 'x-api-key: $MONGODB_EXPORTER_API_KEY'
    __dangerous__body_down_if_text_missing: 'mongodb_up{cluster_role="mongod"} 1'
  - name: Redis
    slug: redis
    url: https://exporters.eciga.consorciociga.gov.br/metrics
    icon: https://redis.io/favicon.ico
    headers:
      - 'x-api-key: $REDIS_EXPORTER_API_KEY'
    __dangerous__body_down_if_text_missing: 'redis_up 1'
status-website:
  cname: status.eciga.consorciociga.gov.br
  css: 'article.up { z-index: -1; } nav { overflow-x: visible !important; }'
  introTitle: '<img alt="Banner do Status do e-Ciga" src="https://i.postimg.cc/XqyxTDbL/Gemini-Generated-Image-mr8ipjmr8ipjmr8i.png" style="width: 100%">'
  js: setTimeout(() => { document.querySelector('a[href="#ciga-apps"]').outerHTML = '<ciga-apps/>' }, 1000)
  logoUrl: https://e2.ciga.sc.gov.br/eciga.webp
  name: Status do e-Ciga
  navbar:
    - title: ''
      href: '#ciga-apps'
  scripts:
    - src: https://apps.consorciociga.gov.br/ciga-apps.js
i18n:
  activeIncidents: Incidentes Ativos
  activeIncidentSummary: Aberto em $DATE com $POSTS atualizações
  allSystemsOperational: Todos os sistemas operacionais
  averageResponseTime: "Tempo médio de resposta: $TIMEms"
  averageResponseTimeTitle: Resposta média
  degraded: Degradado
  down: Fora do ar
  duration: Duração
  duration1Y: 1 ano
  duration24H: 24h
  duration30D: 30d
  duration7D: 7d
  durationAll: tudo
  durationMin: $DURATION minutos
  errorHome: Ir para a página inicial
  errorIntro: Ocorreu um erro ao tentar obter os detalhes mais recentes do status.
  errorText: Você pode tentar novamente em alguns instantes.
  errorTitle: Ocorreu um erro
  footer: ©2025 [Consórcio de Inovação na Gestão Pública](https://consorciociga.gov.br/)
  incidentBack: ← Voltar para todos os incidentes
  incidentClosedAt: Fechado em
  incidentCommentSummary: Postado em $DATE por $AUTHOR
  incidentCompleted: Concluído
  incidentDetails: Detalhes do Incidente
  incidentFixed: Resolvido
  incidentOngoing: Em andamento
  incidentOpenedAt: Aberto em
  incidentReport: "Relatório do incidente #$NUMBER →"
  incidentScheduled: Agendado
  incidentTitle: Detalhes do Incidente $NUMBER
  incidentViewOnGitHub: Ver e Inscrever-se no GitHub
  liveStatus: Status em Tempo Real
  loading: Carregando
  locale: pt-BR
  ms: ms
  navGitHub: GitHub
  overallUptime: "Disponibilidade total: $UPTIME"
  overallUptimeTitle: Disponibilidade total
  pastIncidents: Incidentes Anteriores
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS atualizações
  pastScheduledMaintenance: Manutenções Agendadas Anteriores
  rateLimitExceededCopyPastePAT: Copie e cole seu token
  rateLimitExceededErrorFix: Você pode esperar mais uma hora para que o limite do seu endereço IP seja restaurado. Alternativamente, você pode adicionar seu Token de Acesso Pessoal do GitHub, o que lhe dará 5.000 requisições adicionais por hora.
  rateLimitExceededErrorHowCanFix: Como posso corrigir isso?
  rateLimitExceededErrorMeaning: Este site usa a API do GitHub para acessar dados em tempo real sobre o status de nossos sites. Por padrão, o GitHub permite 60 requisições por hora para cada endereço IP, as quais você já consumiu.
  rateLimitExceededGeneratePAT: Saiba como gerar um Token de Acesso Pessoal
  rateLimitExceededGitHubPAT: Token de Acesso Pessoal do GitHub
  rateLimitExceededHasSet: Você tem um token de acesso pessoal configurado.
  rateLimitExceededIntro: Você excedeu o número de requisições permitidas por hora, então terá que esperar antes de acessar este site novamente. Alternativamente, você pode adicionar um Token de Acesso Pessoal do GitHub para continuar usando este site.
  rateLimitExceededRemoveToken: Remover token
  rateLimitExceededSaveToken: Salvar token
  rateLimitExceededTitle: Limite de requisições excedido
  rateLimitExceededWhatDoesErrorMean: O que significa este erro?
  responseTimeMs: Tempo de resposta (ms)
  scheduledMaintenance: Manutenção Agendada
  scheduledMaintenanceSummaryStarted: Iniciado em $DATE com duração de $DURATION minutos
  scheduledMaintenanceSummaryStarts: Inicia em $DATE com duração de $DURATION minutos
  sevelDayResponseTime: Tempo de resposta (7 dias)
  startedAt: Iniciado em
  startsAt: Inicia em
  up: No ar
